config/routes.rb
Rails.application.routes.draw do
  resources :settings
  resources :transactions
  resources :products do
  	collection do
  		get :to_buy
  		get :send_to_buy
  	end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'products#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
	has_many :transactions
end

app/models/setting.rb
class Setting < ApplicationRecord
	enum :when_send_notification => {:'diariamente' => 1, :'semanalmente' => 7, :'mensalmente' => 30}
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :product

  enum :transaction_type => { :'entrada' => 1, :'saída' => 0}
  validates_presence_of :amount, :transaction_type

  after_create :change_product_stock_create
  after_destroy :change_product_stock_destroy

  private
  	def change_product_stock_create
  		if self.entrada?
  			self.product.stock += self.amount
  		elsif self.saída?
  			self.product.stock -= self.amount
  		end
  		self.product.save
  	end

  	def change_product_stock_destroy
  		if self.entrada?
  			self.product.stock -= self.amount
  		elsif self.saída?
  			self.product.stock += self.amount
  		end
  		self.product.save
  	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  def to_buy
    @products = Product.where("stock <= minimum_stock")
  end

  def send_to_buy
    NotifierMailer.below_minimum_stock.deliver
    redirect_to to_buy_products_path, notice: 'Lista enviada com sucesso'
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Produto cadastrado com sucesso.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Produto atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Produto excluído com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :minimum_stock, :stock)
    end
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  before_action :set_setting, only: [:show, :edit, :update, :destroy]

  # GET /settings
  # GET /settings.json
  def index
    @settings = Setting.all
  end

  # GET /settings/1
  # GET /settings/1.json
  def show
  end

  # GET /settings/new
  def new
    @setting = Setting.new
  end

  # GET /settings/1/edit
  def edit
  end

  # POST /settings
  # POST /settings.json
  def create
    @setting = Setting.new(setting_params)

    respond_to do |format|
      if @setting.save
        format.html { redirect_to @setting, notice: 'Setting was successfully created.' }
        format.json { render :show, status: :created, location: @setting }
      else
        format.html { render :new }
        format.json { render json: @setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /settings/1
  # PATCH/PUT /settings/1.json
  def update
    respond_to do |format|
      if @setting.update(setting_params)
        format.html { redirect_to  edit_setting_path(@setting), notice: 'Configuração atualizada com sucesso.' }
        format.json { render :show, status: :ok, location: @setting }
      else
        format.html { render :edit }
        format.json { render json: @setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /settings/1
  # DELETE /settings/1.json
  def destroy
    @setting.destroy
    respond_to do |format|
      format.html { redirect_to settings_url, notice: 'Setting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_setting
      @setting = Setting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def setting_params
      params.require(:setting).permit(:when_send_notification)
    end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: [:show, :edit, :update, :destroy]

  # GET /transactions
  # GET /transactions.json
  def index
    @transactions = Transaction.all
  end

  # GET /transactions/1
  # GET /transactions/1.json
  def show
  end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
  end

  # GET /transactions/1/edit
  def edit
  end

  # POST /transactions
  # POST /transactions.json
  def create
    @transaction = Transaction.new(transaction_params)

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to @transaction, notice: 'Transação criada com sucesso.' }
        format.json { render :show, status: :created, location: @transaction }
      else
        format.html { render :new }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transactions/1
  # PATCH/PUT /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to @transaction, notice: 'Transação atualizada com sucesso.' }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1
  # DELETE /transactions/1.json
  def destroy
    @transaction.destroy
    respond_to do |format|
      format.html { redirect_to transactions_url, notice: 'Transação excuída com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transaction_params
      params.require(:transaction).permit(:product_id, :amount, :transaction_type)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Controle</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-secondary">
      <div class="container">
        <%= link_to 'Controle de mantimentos', root_path, class: 'navbar-brand' %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <%= link_to 'Produtos', products_path, class: 'nav-link' %>
            </li>
<!--             <li class="nav-item">
              <%= link_to 'Transações', transactions_path, class: 'nav-link' %>
            </li> -->
            <li class="nav-item">
              <%= link_to 'Lista de compras', to_buy_products_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Configuração', edit_setting_path(Setting.first), class: 'nav-link' %>
            </li>
          </ul>
        </div>
      </div>
    </nav> 

    <div class="container">
      <% if alert.present? %>
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
          <%= alert %>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      <% end %>

      <% if notice.present? %>
        <div class="alert alert-success alert-dismissible fade show" role="alert">
          <%= notice %>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/products/_form.html.erb
<%= simple_form_for(@product) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :minimum_stock %>
    <%= f.input :stock %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editar produto</h1>

<%= render 'form', product: @product %>

app/views/products/index.html.erb
<h1>Produtos</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Estoque mínimo</th>
      <th>Stock</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.minimum_stock %></td>
        <td><%= product.stock %></td>
        <td>
          <div class="btn-group btn-group-sm">
            <%= link_to 'Entrada', new_transaction_path(product_id: product.id, transaction_type: 'entrada'), class: 'btn btn-info' %>
            <%= link_to 'Saída', new_transaction_path(product_id: product.id, transaction_type: 'saída'), class: 'btn btn-info' %>
            <%= link_to 'Visualizar', product, class: 'btn btn-secondary' %>
            <%= link_to 'Editar', edit_product_path(product), class: 'btn btn-secondary' %>
            <%= link_to 'Excluír', product, method: :delete, data: { confirm: 'Tem certeza?' }, class: 'btn btn-danger' %>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Cadastrar produto', new_product_path, class: 'btn btn-primary' %>

app/views/products/new.html.erb
<h1>Novo produto</h1>

<%= render 'form', product: @product %>

app/views/products/show.html.erb
<h1>
  <%= @product.name %>
</h1>

<p>
  <strong>Estoque mínimo:</strong>
  <%= @product.minimum_stock %>
</p>

<p>
  <strong>Estoque:</strong>
  <%= @product.stock %>
</p>

<hr>
<h2>Movimentaçãoes</h2>
<%= link_to 'Entrada', new_transaction_path(product_id: @product.id, transaction_type: 'entrada'), class: 'btn btn-info' %>
<%= link_to 'Saída', new_transaction_path(product_id: @product.id, transaction_type: 'saída'), class: 'btn btn-info' %>
<hr>
<table class="table table-bordered">
  <thead>
    <tr>
      <th>Data</th>
      <th>Quantidade</th>
      <th>Tipo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @product.transactions.order(created_at: :desc).each do |transaction| %>
      <tr>
        <td><%= transaction.created_at.strftime("%d/%m/%Y %H:%M") %></td>
        <td><%= transaction.amount %></td>
        <td><%= transaction.transaction_type.titleize %></td>
        <td>
          <div class="btn-group btn-group-sm">
            <%= link_to 'Exibir', transaction, class: 'btn btn-secondary' %>
            <%= link_to 'Editar', edit_transaction_path(transaction), class: 'btn btn-secondary' %>
            <%= link_to 'Excluir', transaction, method: :delete, data: { confirm: 'Tem certeza?' }, class: 'btn btn-danger' %>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/products/to_buy.html.erb
<h1>Lista de compras</h1>

<%= link_to 'Enviar por email', send_to_buy_products_path, class: 'btn btn-info' %>

<br><br>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Estoque mínimo</th>
      <th>Estoque atual</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.minimum_stock %></td>
        <td><%= product.stock %></td>
        <td><%= link_to 'Entrada', new_transaction_path(product_id: product.id, transaction_type: 'entrada'), class: 'btn btn-info' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/settings/_form.html.erb
<%= simple_form_for(@setting) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :when_send_notification, collection: Setting.when_send_notifications.keys.map {|s| [s.titleize,s]} %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/settings/edit.html.erb
<h1>Configurações</h1>

<%= render 'form', setting: @setting %>

app/views/settings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Settings</h1>

<table>
  <thead>
    <tr>
      <th>When send notification</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @settings.each do |setting| %>
      <tr>
        <td><%= setting.when_send_notification %></td>
        <td><%= link_to 'Show', setting %></td>
        <td><%= link_to 'Edit', edit_setting_path(setting) %></td>
        <td><%= link_to 'Destroy', setting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Setting', new_setting_path %>

app/views/settings/new.html.erb
<h1>New Setting</h1>

<%= render 'form', setting: @setting %>

<%= link_to 'Back', settings_path %>

app/views/settings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>When send notification:</strong>
  <%= @setting.when_send_notification %>
</p>

<%= link_to 'Edit', edit_setting_path(@setting) %> |
<%= link_to 'Back', settings_path %>

app/views/transactions/_form.html.erb
<%= simple_form_for(@transaction) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :transaction_type, collection: Transaction.transaction_types.keys.map{|t| [t.titleize, t]}, selected: params[:transaction_type], include_blank: true %>
    <%= f.association :product, selected: params[:product_id], include_blank: true %>
    <%= f.input :amount %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/transactions/edit.html.erb
<h1>Editar transação</h1>

<%= render 'form', transaction: @transaction %>

app/views/transactions/index.html.erb
<h1>Transações</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Poduto</th>
      <th>Quantidade</th>
      <th>Tipo</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @transactions.each do |transaction| %>
      <tr>
        <td><%= transaction.product.name %></td>
        <td><%= transaction.amount %></td>
        <td><%= transaction.transaction_type %></td>
        <td>
          <div class="btn-group btn-group-sm">
            <%= link_to 'Exibir', transaction, class: 'btn btn-secondary' %>
            <%= link_to 'Editar', edit_transaction_path(transaction), class: 'btn btn-secondary' %>
            <%= link_to 'Excluir', transaction, method: :delete, data: { confirm: 'Tem certeza?' }, class: 'btn btn-danger' %>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nova transação', new_transaction_path, class: 'btn btn-primary' %>

app/views/transactions/new.html.erb
<h1>Nova transação</h1>

<%= render 'form', transaction: @transaction %>

app/views/transactions/show.html.erb
<p>
  <strong>Produto:</strong>
  <%= @transaction.product.name %>
</p>

<p>
  <strong>Quantidade:</strong>
  <%= @transaction.amount %>
</p>

<p>
  <strong>Tipo:</strong>
  <%= @transaction.transaction_type %>
</p>